name: Code Coverage

on:
    push:
        branches:
            - master

jobs:
    code_coverage:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            -
                uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.3
                    coverage: pcov
                    tools: composer:v2

            -
                run: composer install --no-progress --ansi

            # https://kizu514.com/blog/pcov-is-better-than-phpdbg-and-xdebug-for-code-coverage/
            -
                run: |
                    vendor/bin/phpunit --coverage-clover build/logs/clover.xml
                    # Coveralls.io
                    composer require --dev php-coveralls/php-coveralls:^2.4
                    vendor/bin/php-coveralls --coverage_clover=build/logs/clover.xml -v
                env:
                    COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
