name: Tests

on:
    pull_request: null

jobs:
    tests:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: ['7.4']
                dependencies: ['locked']
                include:
                    - php: '7.3'
                      dependencies: 'lowest'
                    - php: '8.0'
                      dependencies: 'latest'


        name: PHP ${{ matrix.php }} tests
        steps:
            -   uses: actions/checkout@v2

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none # disable xdebug, pcov

            -   run: composer update --prefer-lowest --no-progress --ansi
                if: "matrix.dependencies == 'lowest'"

            -   run: composer install --no-progress --ansi
                if: "matrix.dependencies == 'locked'"

            -   run: composer install --no-progress --ansi --ignore-platform-req=php
                if: "matrix.dependencies == 'latest'"

            -   run: vendor/bin/phpunit
